<?php

namespace Modules\Crm\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Modules\Crm\Enums\RequestStatus;
use Modules\Crm\Models\Category;
use Modules\Crm\Models\Customer;
use Modules\Crm\Models\CustomerAddress;
use Modules\Crm\Models\CustomerContact;
use Modules\Crm\Models\Payment;
use Modules\Crm\Models\Professional;
use Modules\Crm\Models\ProfessionalAddress;
use Modules\Crm\Models\ProfessionalContact;
use Modules\Crm\Models\Request;
use Modules\Crm\Models\Service;
use Modules\Crm\Models\ServiceRating;
use Modules\Crm\Models\Subscription;
use Modules\Crm\Models\SubscriptionPlan;
use Modules\Crm\Models\UrgencyType;

class SampleDataSeeder extends Seeder
{
    public function run(): void
    {
        $customersCount = 50;
        $professionalsCount = 60;

        Customer::factory()->create([
            'full_name' => 'Alejandro Méndez Customer',
            'first_name' => 'Alejandro',
            'last_name' => 'Méndez Customer',
            'dni' => '12.345.678-1',
        ]);

        Customer::factory()->count($customersCount)->create();

        Professional::factory()->create([
            'full_name' => 'Alejandro Méndez Professional',
            'first_name' => 'Alejandro',
            'last_name' => 'Méndez Professional',
            'dni' => '12.345.678-1',
        ]);
        Professional::factory()->count($professionalsCount)->create();

        Customer::all()->each(function (Customer $c) {
            CustomerContact::factory()->count(random_int(1, 2))->create(['customer_id' => $c->id]);
            CustomerAddress::factory()->count(random_int(1, 2))->create(['customer_id' => $c->id]);
        });

        Professional::all()->each(function (Professional $p) {
            ProfessionalContact::factory()->count(random_int(1, 2))->create(['professional_id' => $p->id]);
            ProfessionalAddress::factory()->count(random_int(1, 2))->create(['professional_id' => $p->id]);
        });

        $categories = Category::all();
        Professional::all()->each(function (Professional $p) use ($categories) {
            $attach = $categories->random($categories->count() ? min(3, $categories->count()) : 0)->pluck('id')->all();
            if (count($attach)) {
                $p->categories()->syncWithoutDetaching($attach);
            }
        });

        $urgency = UrgencyType::all()->keyBy('id');

        Customer::all()->each(function (Customer $c) use ($categories, $urgency) {
            $activeMade = Request::where('customer_id', $c->id)
                ->whereIn('status', [RequestStatus::Pending->value, RequestStatus::Active->value])
                ->exists();
            $count = random_int(1, 3);
            for ($i = 0; $i < $count; $i++) {
                $cat = $categories->random();
                $urg = $urgency->random();
                $status = $activeMade ? RequestStatus::Rejected->value : collect([RequestStatus::Pending->value, RequestStatus::Active->value, RequestStatus::Rejected->value])->random();
                if (in_array($status, [RequestStatus::Pending->value, RequestStatus::Active->value])) {
                    if ($activeMade) {
                        $status = RequestStatus::Rejected->value;
                    } else {
                        $activeMade = true;
                    }
                }

                $assigned = null;
                if ($status !== RequestStatus::Rejected->value) {
                    $assigned = Professional::query()
                        ->whereHas('categories', function ($q) use ($cat) {
                            $q->where('categories.id', $cat->id);
                        })
                        ->inRandomOrder()
                        ->value('id');
                }

                $priority = $urg->priority_weight;
                $slaDue = now()->addHours($urg->sla_hours);
                $acceptedAt = $status === RequestStatus::Active->value ? now()->subHours(random_int(1, 48)) : null;

                Request::create([
                    'customer_id' => $c->id,
                    'category_id' => $cat->id,
                    'urgency_type_id' => $urg->id,
                    'professional_id' => $assigned,
                    'description' => 'Autogenerated request for '.$cat->name,
                    'address' => fake()->streetAddress(),
                    'status' => $status,
                    'priority' => $priority,
                    'sla_due_at' => $slaDue,
                    'accepted_at' => $acceptedAt,
                ]);
            }
        });

        Request::query()->where('status', 'active')->get()->each(function (Request $r) {
            if ($r->professional_id && !Service::where('request_id', $r->id)->exists()) {
                Service::create([
                    'request_id' => $r->id,
                    'customer_id' => $r->customer_id,
                    'professional_id' => $r->professional_id,
                    'status' => 'active',
                    'started_at' => now()->subHours(random_int(1, 48)),
                    'completed_at' => null,
                ]);
            }
        });

        $plans = SubscriptionPlan::all();
        Professional::all()->each(function (Professional $p) use ($plans) {
            $subsCount = random_int(1, 3);
            $activeSet = Subscription::where('professional_id', $p->id)
                ->where('status', 'active')
                ->exists();
            for ($i = 0; $i < $subsCount; $i++) {
                $plan = $plans->random();
                $status = $activeSet ? collect(['pending', 'rejected'])->random() : collect(['pending', 'active', 'rejected'])->random();
                if ($status === 'active') {
                    $activeSet = true;
                }
                $activeAt = $status === 'active' ? now()->subDays(random_int(1, 30)) : null;
                $expiresAt = $status === 'active' ? (clone $activeAt)->addMonths($plan->duration_months) : null;

                Subscription::create([
                    'professional_id' => $p->id,
                    'subscription_plan_id' => $plan->id,
                    'status' => $status,
                    'active_at' => $activeAt,
                    'expires_at' => $expiresAt,
                ]);
            }
        });

        Subscription::all()->each(function (Subscription $s) {
            $paymentsCount = random_int(0, 2);
            for ($i = 0; $i < $paymentsCount; $i++) {
                Payment::factory()->create([
                    'professional_id' => $s->professional_id,
                    'subscription_id' => $s->id,
                ]);
            }
        });

        Service::all()->each(function (Service $svc) {
            if (!ServiceRating::where('service_id', $svc->id)->exists() && random_int(0, 1)) {
                ServiceRating::factory()->create([
                    'service_id' => $svc->id,
                    'customer_id' => $svc->customer_id,
                ]);
            }
        });
    }
}
